# Generated by Django 4.1.7 on 2023-04-01 01:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.CharField(max_length=300)),
                ('picture', models.ImageField(upload_to='uploads/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2023, 4, 1, 1, 44, 9, 604884))),
                ('description', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='uploads/')),
                ('charity', models.CharField(choices=[(1, 'Boys & Girls Club of SB'), (2, 'SB Center for the Homeless'), (3, 'American Red Cross'), (4, 'Salvation Army'), (5, 'Native American Rights Fund'), (6, "St. Jude Children's Research Hospital"), (7, 'Habitat for Humanity'), (8, 'Wounded Warrior Project'), (9, 'Humane Society'), (10, 'Special Olympics')], max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='HappyHobby.profile')),
                ('registered_users', models.ManyToManyField(related_name='registered_users', to='HappyHobby.profile')),
                ('tags', models.ManyToManyField(to='HappyHobby.tags')),
            ],
        ),
    ]
