# Generated by Django 4.1.7 on 2023-04-01 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHobby', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 1, 47, 9, 746858)),
        ),
    ]
