# Generated by Django 4.1 on 2023-04-01 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHobby', '0002_alter_event_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 1, 56, 10, 579332)),
        ),
    ]
