# Generated by Django 4.1.7 on 2023-04-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHobby', '0004_alter_event_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='profile_pics'),
        ),
    ]
