# Generated by Django 4.1.7 on 2023-04-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHobby', '0005_image_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
