# Generated by Django 4.1.7 on 2023-04-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHobby', '0006_alter_profile_picture_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='image.jpg', null=True, upload_to='images'),
        ),
    ]
