# Generated by Django 4.1.7 on 2023-04-01 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHobby', '0007_alter_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('image', models.ImageField(default='image.jpg', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='HappyHobby.image'),
        ),
    ]
