# Generated by Django 4.1.2 on 2023-04-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHobby', '0009_remove_profile_password_remove_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='picture',
        ),
        migrations.AddField(
            model_name='event',
            name='raised_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='charity',
            field=models.CharField(choices=[('1', 'Boys & Girls Club of SB'), ('2', 'SB Center for the Homeless'), ('3', 'American Red Cross'), ('4', 'Salvation Army'), ('5', 'Native American Rights Fund'), ('6', "St. Jude Children's Research Hospital"), ('7', 'Habitat for Humanity'), ('8', 'Wounded Warrior Project'), ('9', 'Humane Society'), ('10', 'Special Olympics')], max_length=50),
        ),
    ]
