# Generated by Django 4.1.7 on 2023-04-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHobby', '0014_alter_event_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_title',
            field=models.CharField(default='title', max_length=50),
            preserve_default=False,
        ),
    ]
