# Generated by Django 4.1.7 on 2023-04-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HappyHobby', '0015_event_event_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
